"""added is_active field to couples table

Revision ID: 012a516a5919
Revises: 6412ecb50dcd
Create Date: 2025-09-02 11:42:53.026746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012a516a5919'
down_revision: Union[str, Sequence[str], None] = '6412ecb50dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couples', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couples', 'is_active')
    # ### end Alembic commands ###

